language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

addons:
  hosts:
    - ecag-fixml-dev1

before_install:
  - docker pull ecdb/fixml:sim

install:
  - docker run -d -p 35672:5672 -p 35671:5671 ecdb/fixml:sim

script:
   - mvn -P integration-test verify
