version: 2
jobs:
  build:
    machine: true 
    steps:
      - checkout
      - run: sudo hostnamectl set-hostname ecag-fixml-dev1
      - run: sudo sed -i 's/127.0.0.1 localhost/127.0.0.1 localhost ecag-fixml-dev1/g' /etc/hosts 
      - run: docker run -dh ecag-fixml-dev1 -p 35671:10000 -p 35672:20000 -p 40000:40000 -p 50000:22 --name=fixml vyboant/fixml_test
      - run: sleep 10 
#      - run: hostname
#      - run: cat /etc/hostname
#      - run: cat /etc/hosts
#      - run: ping -c 5 ecag-fixml-dev1
#      - run: nc -zv ecag-fixml-dev1 35671
#      - run: nc -zv ecag-fixml-dev1 35672
      - run: mvn -P integration-test verify



#machine:
#  hosts:
#    ecag-fixml-dev1: 127.0.0.1
#  java:
#    version: oraclejdk8
#  services:
#    - docker
#
#test:
#  pre:
#    - docker run -d -p 35672:5672 -p 35671:5671 ecmi/fixml:sim
#  override:
#    - mvn -P integration-test verify
#  post:
#    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
#    - find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
#    - mkdir -p $CIRCLE_ARTIFACTS/coverage/1.0/
#    - cp -r qpid-jms/target/site/jacoco/* $CIRCLE_ARTIFACTS/coverage/1.0/
#